### ISSUE TITLE
All the label is zero?

### ISSUE THREAD

**Issue by wll969** [DavidMcDonald1993/heat#2]
Hi I am very interested in your project. In your main.py, train_y = np.zeros([len(train_x), 1, 1], dtype=np.int32 )  , the train_y is the label right? why the label for all the positive and negative label are all 0? Thanks!

**Comment by DavidMcDonald1993** [comment]
Hi,

train_y is a set of dummy labels since the training is done in an unsupervised way.
I use this because the positive sample is always the sample at index 0 and so this is the output to maximize. Since I am using sparse softmax I only need to supply the index of the positive label.

Best wishes,
David

________________________________

**Comment by wll969** [comment]
Thank you, that makes a lot of sense! I just got a new question: Is there a reason for the duplicate pairs of (u,v) in the positive samples of training?  I guess if (u,v) appears more means the linkage between u and v are more important?

**Comment by DavidMcDonald1993** [comment]
Hi,

We add (v, u) for every (u, v) because we are dealing with undirected networks and would like a chance for both u and v to be source nodes.

David
________________________________

**Comment by wll969** [comment]
Thank you but actually I mean... in your utils.py function  determine_positive_and_negative_samples, every time you append (u,v) to the positive samples, it seems that you didn't check if (u,v) already been added to positive samples by a previous random walk. I guess you did this for a reason? Because if (u,v) appear more in positive samples indicates a stronger linkage between u and v?

**Comment by DavidMcDonald1993** [comment]
I do this before performing random walks (I add the edge set into the set of positive samples before performing walks).

________________________________

**Comment by wll969** [comment]
Thank you!
